- name: apt install git
  apt: name={{item}} state=installed
  with_items:
    - git
- name: mkdir ./download and link it under /workspace/
  shell: |
    mkdir -p download &&
    ln -sf `pwd`/download /workspace/download
  tags:
    - link
    - download
- name: get http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-1.02.tar.xz
  get_url:
    url: http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-1.02.tar.xz
    dest: /workspace/download/
  tags:
    - jumanpp
    - download
- name: get http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2
  get_url:
    url: http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2
    dest: /workspace/download/
  tags:
    - juman
    - download
- name: get http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/knp/knp-4.17.tar.bz2
  get_url:
    url: http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/knp/knp-4.17.tar.bz2
    dest: /workspace/download/
  tags:
    - knp
    - download
- name: get http://lotus.kuee.kyoto-u.ac.jp/nl-resource/pyknp/pyknp-0.3.tar.gz
  get_url:
    url: http://lotus.kuee.kyoto-u.ac.jp/nl-resource/pyknp/pyknp-0.3.tar.gz
    dest: /workspace/download/
  tags:
    - pyknp
    - download
- name: git clone fastText
  git:
    repo: https://github.com/facebookresearch/fastText.git
    dest: /workspace/download/fastText
  tags:
    - fasttext
    - download
