language: python
python:
  - "3.5"
install: "pip3 install -r requirements.txt"

services:
  - docker

script:
  - ansible-container build &&
    docker tag nlp-doc2vec:latest vochicong/nlp-doc2vec:latest

after_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push vochicong/nlp-doc2vec:latest
