# Use curl and rm to save disk space and docker size
- name: Download JUMAN
  shell: curl -SL http://nlp.ist.i.kyoto-u.ac.jp/nl-resource/juman/juman-7.01.tar.bz2 | tar xjC /workspace
  tags:
    - juman
    - download
- name: Install JUMAN
  shell: |
    cd /workspace/juman-7.01 &&
    ./configure &&
    make &&
    make install
  tags:
    - juman
    - install
- name: Clean JUMAN
  command: rm -rf /workspace/juman-7.01
  tags:
    - juman
    - clean
