# Python2 is needed for some pip packages like
# pattern, fast version of gensim
- name: Install python2 pip and venv
  apt: name={{item}} state=installed update_cache=yes
  with_items:
    - python-pip
    - python-virtualenv
  tags:
    - apt
    - python2
- name: Create venv
  shell: |
    virtualenv /workspace/venv/nlp-p2 &&
    source /workspace/venv/nlp-p2/bin/activate &&\
    pip install --upgrade pip
  args:
    executable: /bin/bash
  tags:
    - venv
    - python2
    - pip
- name: apt clean
  shell: apt clean && rm -rf /var/lib/apt/lists/*
  tags:
    - clean
    - python2
