- name: Install python3, pip, venv, ansible
  apt: name={{item}} state=installed update_cache=true
  with_items:
    - python3-pip
    - python3-venv
    - ansible-container
    - git
  tags:
    - apt
    - ansible-container
- name: git clone ansible container
  git:
    repo: https://github.com/ansible/ansible-container.git
    dest: /workspace/ansible-container
  tags:
    - ansible-container
    - download
- name: Install ansible container
  shell: |
    unset PYTHONPATH &&
    python3 -m venv /workspace/venv/ansible &&
    source /workspace/venv/ansible/bin/activate &&
    pip3 install -U pip &&
    pip3 install -e /workspace/ansible-container[docker]
  args:
    executable: /bin/bash
  tags:
    - ansible-container
