# Use curl and rm to save disk space and docker size
- name: Download PYKNP
  command: curl -SL http://lotus.kuee.kyoto-u.ac.jp/nl-resource/pyknp/pyknp-0.3.tar.gz | tar xzC /workspace
  tags:
    - pyknp
    - download
- name: Install PYKNP
  shell: |
    unset PYTHONPATH &&
    source /workspace/venv/nlp/bin/activate &&
    cd /workspace/pyknp-0.3 &&
    python3 setup.py install
    source /workspace/venv/nlp-p2/bin/activate &&
    python setup.py install
  args:
    executable: /bin/bash
  tags:
    - pyknp
    - pip
- name: Clean PYKNP
  command: rm -rf /workspace/pyknp-0.3
  tags:
    - pyknp
    - clean
