- name: Install PYKNP
  shell: |
    # Use curl and rm to save disk space and docker size
    curl -SL http://lotus.kuee.kyoto-u.ac.jp/nl-resource/pyknp/pyknp-0.3.tar.gz | tar xvzC /workspace &&
    unset PYTHONPATH &&
    source /workspace/python3-venv/bin/activate &&
    cd /workspace/pyknp-0.3 &&
    python3 setup.py install &&
    rm -rf /workspace/pyknp-0.3
  args:
    executable: /bin/bash
  tags:
    - pyknp
