# Use curl and rm to save disk space and docker size
- name: Download JUMANPP
  shell: curl -SL http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-1.02.tar.xz | tar xJC /workspace
  tags:
    - jumanpp
    - download
- name: Install JUMANPP
  shell: |
    cd /workspace/jumanpp-1.02 &&
    ./configure &&
    make &&
    make install
  tags:
    - jumanpp
    - install
- name: Clean JUMANPP
  command: rm -rf /workspace/jumanpp-1.02
  tags:
    - jumanpp
    - clean
